Algoritmo "idades"

Var
nome1, nome2 : caractere
idade1, idade2 : inteiro
media : real


Inicio
Escreval("Dados da primeira pessoa: ")
Escreva("Nome: ")
leia(nome1)
Escreva("Idade: ")
leia(idade1)

Escreval("Dados da segunda pessoa: ")
Escreva("Nome: ")
leia(nome2)
Escreva("Idade: ")
leia(idade2)

media <- (idade1 + idade2)/2

escreva("A idade média de ", nome1, " e ", nome2, " é de ", media, " anos")



Fimalgoritmo